### ISSUE TITLE
Write Browser Plugin to Remove Drone License Banner

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#239]

**Comment by wgsuse** [comment]
As [mentioned in the chat](https://suse.slack.com/archives/C03FD9J62SC/p1692900737383109?thread_ts=1692898200.698369&cid=C03FD9J62SC):

I installed the [Styler chrome extension](https://chrome.google.com/webstore/detail/styler-beta/hbhkfnpodhdcaophahpkiflechaoddoi/related) and added [@Brooks Newberry](https://suse.slack.com/team/U0303P1NH42) CSS snippet. Now the banner is gone!
 
 ```css
/* drone */
[class^="license_system-messages-wrapper"] {
  display: none;
}
 ```
 
![image](https://github.com/rancher/ecm-distro-tools/assets/100312460/0d7d81ad-bdc6-4235-83d4-b468cd5ac1a7)
