### ISSUE TITLE
Create rancher release command line to check RCs and Dev deps

### ISSUE THREAD

**Issue by johnatasr** [rancher/ecm-distro-tools#272]
With ecm-distro-tools gh action created we could simplify this script https://github.com/rancher/rancher/pull/42773/files, could be used as a command in ecm-distro-tools.

Example of action

```
name: Final release actions

on:
  workflow_dispatch:
  release:
    types: [prereleased]
  pull_request:

env:
  RELEASE_TITLE: ${{ github.event.release.name || '' }}

jobs:
  check-deps-and-tags:
    runs-on: ubuntu-latest

    steps:
      -
        name: setup ecm-distro-tools
        uses: rancher/ecm-distro-tools
        with:
          version: v0.23.0
        env:
           GH_TOKEN: ${{ github.token }}
      -
        name: Verify dependencies files in a final release candidate
        run: rancher-release check-deps-rcs --commit ${{ env.GITHUB_SHA }}
```
