### ISSUE TITLE
Combine Chart Versions and Image Versions into 1 File

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#357]
So right now we have chart versions and images versions scattered through different files in rke2:
chart versions: https://github.com/rancher/rke2/blob/master/charts/chart_versions.yaml
images versions: https://github.com/rancher/rke2/blob/master/scripts/build-images

Have just one file that is similar to kdm but simpler of course, that should look like this:

```yaml
charts:
- vshpere-cpi:
    version: 1.5.100
    chart: /charts/rancher-vsphere-cpi.yaml
    images:
      mirrored-cloud-provider-vsphere-cpi-release-manager:
        repo: ${REGISTRY}/rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.26.1
```

maybe a variation of this to include also core images like kuberntes image, and otheres
